// @vitest-environment node
import { describe, expect, it, beforeAll, afterAll } from "vitest";
import { PrismaClient } from "@/generated/prisma/client";
import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";
import { PrismaUnitOfWorkAdapter } from "../database/prisma-unit-of-work-adapter";
import { PrismaAttemptRepository } from "./prisma-attempt-repository";
import { PrismaDailySessionRepository } from "./prisma-daily-session-repository";
import { PrismaLessonProgressRepository } from "./prisma-lesson-progress-repository";
import { PrismaPracticeRunRepository } from "./prisma-practice-run-repository";
import { PrismaProgressRepository } from "./prisma-progress-repository";
import { PrismaReviewRepository } from "./prisma-review-repository";
import { PrismaSavedLessonRepository } from "./prisma-saved-lesson-repository";
import { PrismaUserSettingsRepository } from "./prisma-user-settings-repository";
import { UserSettings } from "@/core/account/domain/user-settings";
import { SavedLesson } from "@/core/account/domain/saved-lesson";
import { DailySession } from "@/core/learning/domain/daily-session";
import { PracticeRun } from "@/core/practice/domain/practice-run";
import { ActivityAttempt } from "@/core/practice/domain/activity-attempt";
import { ReviewItem } from "@/core/progress/domain/review-item";

const enabled = process.env.RUN_DB_INTEGRATION === "1";
const describeDatabase = enabled ? describe : describe.skip;

describeDatabase("Prisma repository contracts on SQLite", () => {
  let prisma: PrismaClient;
  let userId: string;

  beforeAll(async () => {
    prisma = new PrismaClient({ adapter: new PrismaBetterSqlite3({ url: process.env.TEST_DATABASE_URL ?? "file:./test-repositories.db" }) });
    await prisma.rateLimitBucket.deleteMany();
    await prisma.catalogPublication.deleteMany();
    await prisma.practiceRunItem.deleteMany();
    await prisma.activityVersion.deleteMany();
    await prisma.catalogRelease.deleteMany();
    await prisma.activity.deleteMany();
    await prisma.activityType.deleteMany();
    await prisma.evaluatorStrategy.deleteMany();
    await prisma.cefrLevel.deleteMany();
    await prisma.editorialStatus.deleteMany();
    await prisma.activityAttempt.deleteMany();
    await prisma.dailySessionLesson.deleteMany();
    await prisma.dailySession.deleteMany();
    await prisma.practiceRun.deleteMany();
    await prisma.reviewItem.deleteMany();
    await prisma.taxonomyProgress.deleteMany();
    await prisma.userActivityProgress.deleteMany();
    await prisma.userLessonProgress.deleteMany();
    await prisma.savedLesson.deleteMany();
    await prisma.userSettings.deleteMany();
    await prisma.session.deleteMany();
    await prisma.account.deleteMany();
    await prisma.verification.deleteMany();
    await prisma.user.deleteMany();
    userId = "integration-user";
    await prisma.user.create({ data: { id: userId, name: "Integration", email: "integration@example.com" } });
  });

  afterAll(async () => prisma.$disconnect());

  it("covers CRUD/upsert and user isolation across repositories", async () => {
    const settings = new PrismaUserSettingsRepository(prisma);
    const saved = new PrismaSavedLessonRepository(prisma);
    const lessons = new PrismaLessonProgressRepository(prisma);
    const sessions = new PrismaDailySessionRepository(prisma);
    const runs = new PrismaPracticeRunRepository(prisma);
    const attempts = new PrismaAttemptRepository(prisma);
    const progress = new PrismaProgressRepository(prisma);
    const reviews = new PrismaReviewRepository(prisma);

    await settings.save(UserSettings.defaults(userId));
    expect((await settings.findByUserId(userId))?.userId).toBe(userId);
    await saved.save(SavedLesson.create({ userId, lessonId: "lesson-1", savedAt: "2026-08-03T00:00:00.000Z" }));
    expect(await saved.findByUserId(userId)).toHaveLength(1);
    expect(await saved.findByUserAndLesson(userId, "lesson-1")).not.toBeNull();
    expect(await saved.findByUserAndLesson(userId, "missing-lesson")).toBeNull();
    await saved.delete(userId, "lesson-1");
    expect(await saved.findByUserId(userId)).toHaveLength(0);
    await saved.save(SavedLesson.create({ userId, lessonId: "lesson-1", savedAt: "2026-08-03T00:00:00.000Z" }));
    await lessons.upsert({ userId, lessonId: "lesson-1", viewed: true, viewedAt: "2026-08-03T00:00:00.000Z", errorsPending: 0 });
    await lessons.upsert({ userId, lessonId: "lesson-2", viewed: false, viewedAt: null, errorsPending: 2 });
    expect((await lessons.findByUserId(userId)).map((item) => item.viewed)).toEqual([true, false]);
    const session = DailySession.create({ id: "session-integration", userId, date: "2026-08-03", status: "lesson", datasetVersion: "v1", seed: "seed", lessons: [{ lessonId: "lesson-1", order: 0, status: "pending", selectionReason: "new", completedAt: null }], practiceRunId: null, createdAt: "2026-08-03T00:00:00.000Z" });
    await sessions.save(session);
    expect((await sessions.findByUserIdAndDate(userId, "2026-08-03"))?.id).toBe(session.id);
    const run = PracticeRun.create({ id: "run-integration", userId, mode: "FOCUSED", scope: { level: "B1", taxonomyNodeId: "topic", taxonomyPath: [], descendantIds: ["topic"], requestedCount: 1 }, activityIds: ["activity-1"], currentIndex: 0, status: "in_progress", datasetVersion: "v1", dailySessionId: null, createdAt: "2026-08-03T00:00:00.000Z" });
    await runs.save(run);
    expect(await runs.findById("missing-run")).toBeNull();
    expect((await runs.findById(run.id))?.activityIds).toEqual(["activity-1"]);
    await prisma.activityType.create({ data: { code: "choice" } });
    await prisma.evaluatorStrategy.create({ data: { code: "single_option" } });
    await prisma.cefrLevel.create({ data: { code: "B1" } });
    await prisma.editorialStatus.create({ data: { code: "published" } });
    await prisma.activity.create({ data: { id: "activity-1" } });
    const release = await prisma.catalogRelease.create({ data: { id: "release-integration", datasetVersion: "v1", checksum: "catalog-checksum", status: "published", publishedAt: new Date("2026-08-03T00:00:00.000Z") } });
    await prisma.catalogPublication.create({ data: { id: "active", releaseId: release.id } });
    await prisma.activityVersion.create({ data: { id: "activity-version-integration", releaseId: release.id, activityId: "activity-1", checksum: "activity-checksum", activityTypeCode: "choice", evaluatorStrategyCode: "single_option", levelCode: "B1", category: "grammar", topic: "topic", subtopic: "topic", difficulty: 1, instructions: "Choose", prompt: "Prompt", passage: null, explanation: "Explanation", tags: "[]", lessonIds: "[]", estimatedSeconds: 10, evaluatorData: "{}", statusCode: "published" } });
    const publishedRun = PracticeRun.create({ id: "run-published-version", userId, mode: "FOCUSED", scope: { level: "B1", taxonomyNodeId: "topic", taxonomyPath: [], descendantIds: ["topic"], requestedCount: 1 }, activityIds: ["activity-1"], currentIndex: 0, status: "in_progress", datasetVersion: "v1", dailySessionId: null, createdAt: "2026-08-03T00:00:00.000Z" });
    await runs.save(publishedRun);
    expect((await prisma.practiceRunItem.findUnique({ where: { practiceRunId_position: { practiceRunId: publishedRun.id, position: 0 } } }))?.activityVersionId).toBe("activity-version-integration");
    const statusRun = PracticeRun.create({ id: "run-statuses", userId, mode: "FOCUSED", scope: { level: "B1", taxonomyNodeId: "topic", taxonomyPath: [], descendantIds: ["topic"], requestedCount: 2 }, activityIds: ["activity-1", "activity-2"], currentIndex: 0, status: "in_progress", datasetVersion: "v1", dailySessionId: null, createdAt: "2026-08-03T00:00:00.000Z" });
    await runs.save(statusRun);
    statusRun.advance();
    await runs.save(statusRun);
    await expect(prisma.practiceRunItem.findUnique({ where: { practiceRunId_position: { practiceRunId: statusRun.id, position: 0 } } })).resolves.toMatchObject({ status: "answered" });
    await attempts.save(ActivityAttempt.create({ id: "attempt-integration", userId, practiceRunId: run.id, activityId: "activity-1", origin: "FOCUSED", idempotencyKey: "key", response: { kind: "boolean", value: true }, isCorrect: true, evaluatorVersion: "1", submittedAt: "2026-08-03T00:00:00.000Z" }));
    expect(await attempts.findByUserIdAndIdempotencyKey(userId, "key")).toMatchObject({ id: "attempt-integration", activityId: "activity-1" });
    expect(await attempts.findByUserIdAndIdempotencyKey(userId, "missing-key")).toBeNull();
    expect(await attempts.findByPracticeRunId(run.id)).toHaveLength(1);
    expect(await attempts.findByUserIdAndActivityId(userId, "activity-1")).toHaveLength(1);
    expect(await attempts.findByUserIdAndActivityId(userId, "activity-1", 0)).toHaveLength(0);
    await progress.upsertActivityProgress({ userId, activityId: "activity-1", attemptsCount: 1, correctCount: 1, lastResult: true, lastAttemptAt: "2026-08-03T00:00:00.000Z" });
    await progress.upsertActivityProgress({ userId, activityId: "activity-2", attemptsCount: 2, correctCount: 1, lastResult: false, lastAttemptAt: null });
    await progress.upsertTaxonomyProgress({ userId, taxonomyNodeId: "topic", attemptsCount: 1, correctCount: 1 });
    expect((await progress.getActivityProgress(userId, "activity-1"))?.correctCount).toBe(1);
    expect(await progress.getActivityProgress(userId, "missing-activity")).toBeNull();
    expect(await progress.getTaxonomyProgress(userId, "missing-topic")).toBeNull();
    await progress.upsertTaxonomyProgress({ userId, taxonomyNodeId: "zero-topic", attemptsCount: 0, correctCount: 0 });
    await progress.upsertTaxonomyProgress({ userId, taxonomyNodeId: "weak-topic", attemptsCount: 10, correctCount: 4 });
    await progress.upsertTaxonomyProgress({ userId, taxonomyNodeId: "middle-topic", attemptsCount: 10, correctCount: 6 });
    await progress.upsertTaxonomyProgress({ userId, taxonomyNodeId: "strong-topic", attemptsCount: 10, correctCount: 8 });
    await expect(progress.getOverview(userId)).resolves.toMatchObject({ totalActivitiesCompleted: 2, totalCorrect: 2, totalAttempts: 3, strongTopicIds: ["strong-topic", "topic"], weakTopicIds: ["weak-topic"] });
    expect(await progress.getOverview("other-user")).toMatchObject({ totalActivitiesCompleted: 0, strongTopicIds: [], weakTopicIds: [] });
    await reviews.save(ReviewItem.create({ id: "review-integration", userId, activityId: "activity-1", taxonomyNodeId: "topic", level: "B1", stage: 0, consecutiveCorrect: 0, dueAt: "2026-08-03T00:00:00.000Z", failedAt: "2026-08-03T00:00:00.000Z", resolvedAt: null, attemptsCount: 1 }));
    expect(await reviews.findDueByUserId(userId, "2026-08-04T00:00:00.000Z")).toHaveLength(1);
    expect(await settings.findByUserId("other-user")).toBeNull();
    expect(await sessions.findById("missing-session")).toBeNull();
    expect(await sessions.findByPracticeRunId("missing-run")).toBeNull();
    const completedSession = DailySession.create({ id: session.id, userId, date: session.date, status: "lesson", datasetVersion: "v1", seed: "seed", lessons: [{ lessonId: "lesson-1", order: 0, status: "completed", selectionReason: "new", completedAt: "2026-08-03T11:00:00.000Z" }], practiceRunId: run.id, createdAt: "2026-08-03T00:00:00.000Z" });
    await sessions.save(completedSession);
    await expect(sessions.findByPracticeRunId(run.id)).resolves.toMatchObject({ id: session.id, practiceRunId: run.id, lessons: [{ completedAt: "2026-08-03T11:00:00.000Z" }] });
    const emptyRun = PracticeRun.create({ id: "run-zero-original", userId, mode: "FOCUSED", scope: { level: "B1", taxonomyNodeId: "topic", taxonomyPath: [], descendantIds: ["topic"], requestedCount: 1 }, activityIds: ["activity-2"], originalActivityCount: 0, currentIndex: 0, status: "in_progress", datasetVersion: "v1", dailySessionId: null, createdAt: "2026-08-03T00:00:00.000Z" });
    await runs.save(emptyRun);
    expect((await runs.findById(emptyRun.id))?.originalActivityCount).toBe(0);
  });

  it("rolls back writes made through the real transaction client", async () => {
    const unitOfWork = new PrismaUnitOfWorkAdapter(prisma);
    const settings = new PrismaUserSettingsRepository(prisma);
    await prisma.userSettings.deleteMany({ where: { userId } });
    await expect(unitOfWork.transaction(async () => {
      await settings.save(UserSettings.defaults(userId));
      throw new Error("force rollback");
    })).rejects.toMatchObject({ message: "force rollback" });
    await prisma.userSettings.deleteMany({ where: { userId } });
    expect(await settings.findByUserId(userId)).toBeNull();
  });
});
